# Generated by Django 5.2.1 on 2025-06-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pams', '0001_initial'),
    ]

    operations = [
    ]
